In [12]:
import pandas as pd
import numpy as np
data1=pd.read_csv("order.csv")
data2=pd.read_csv("product.csv")
print(data1)

   OrderID CustomerID ProductID  Quantity   OrderDate
0     1001        C01       P01         2  2026-01-05
1     1002        C02       P02         1  2026-01-08
2     1003        C01       P03         3  2026-01-12
3     1004        C03       P01         1  2026-02-02
4     1005        C04       P04         2  2026-02-10
5     1006        C02       P03         2  2026-02-15
6     1007        C05       P02         1  2026-03-03
7     1008        C03       P04         4  2026-03-10

In [15]:
data1["OrderID"].count()

np.int64(8)

In [16]:
data1["Quantity"].sum()

np.int64(16)

In [17]:
data1.groupby("CustomerID")["OrderID"].count()

CustomerID
C01    2
C02    2
C03    2
C04    1
C05    1
Name: OrderID, dtype: int64

In [18]:
data1.groupby("OrderDate")["OrderID"].count()

OrderDate
2026-01-05    1
2026-01-08    1
2026-01-12    1
2026-02-02    1
2026-02-10    1
2026-02-15    1
2026-03-03    1
2026-03-10    1
Name: OrderID, dtype: int64

In [20]:
data2

  ProductID   Product     Category  Price
0       P01    Laptop  Electronics  60000
1       P02    Mobile  Electronics  25000
2       P03     Mouse  Accessories    800
3       P04  Keyboard  Accessories   1500

In [23]:
highest_product=data2[data2["Price"]>=60000]

In [24]:
highest_product

  ProductID Product     Category  Price
0       P01  Laptop  Electronics  60000

In [25]:
category_wise=data2[data2["Price"]==60000]

In [26]:
category_wise

  ProductID Product     Category  Price
0       P01  Laptop  Electronics  60000

In [27]:

df = pd.merge(data1, data2, on="ProductID")

print(df)

   OrderID CustomerID ProductID  Quantity   OrderDate   Product     Category  \
0     1001        C01       P01         2  2026-01-05    Laptop  Electronics
1     1002        C02       P02         1  2026-01-08    Mobile  Electronics
2     1003        C01       P03         3  2026-01-12     Mouse  Accessories
3     1004        C03       P01         1  2026-02-02    Laptop  Electronics
4     1005        C04       P04         2  2026-02-10  Keyboard  Accessories
5     1006        C02       P03         2  2026-02-15     Mouse  Accessories
6     1007        C05       P02         1  2026-03-03    Mobile  Electronics
7     1008        C03       P04         4  2026-03-10  Keyboard  Accessories

   Price
0  60000
1  25000
2    800
3  60000
4   1500
5    800
6  25000
7   1500

In [28]:
df["Total_Sales"] = df["Price"] * df["Quantity"]

print(df)

   OrderID CustomerID ProductID  Quantity   OrderDate   Product     Category  \
0     1001        C01       P01         2  2026-01-05    Laptop  Electronics
1     1002        C02       P02         1  2026-01-08    Mobile  Electronics
2     1003        C01       P03         3  2026-01-12     Mouse  Accessories
3     1004        C03       P01         1  2026-02-02    Laptop  Electronics
4     1005        C04       P04         2  2026-02-10  Keyboard  Accessories
5     1006        C02       P03         2  2026-02-15     Mouse  Accessories
6     1007        C05       P02         1  2026-03-03    Mobile  Electronics
7     1008        C03       P04         4  2026-03-10  Keyboard  Accessories

   Price  Total_Sales
0  60000       120000
1  25000        25000
2    800         2400
3  60000        60000
4   1500         3000
5    800         1600
6  25000        25000
7   1500         6000

In [31]:
f=df.to_csv("cleaned_sales.csv", index=False)

In [32]:
f